# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-25 08:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deck_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kingdoms_Cards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='card',
            name='kingdoms',
        ),
        migrations.AddField(
            model_name='kingdoms_cards',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='deck_manager.Card'),
        ),
        migrations.AddField(
            model_name='kingdoms_cards',
            name='kingdom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='deck_manager.Kingdom'),
        ),
    ]
