# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-27 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deck_manager', '0004_kingdom_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='kingdom',
            name='notes',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
